import { chromium, expect, request } from '@playwright/test';
import { randomBytes } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import 'dotenv/config';
const base = process.env.BASE_URL || 'http://localhost:3000';
const phone = '09000000000';
const records = { createdAdmin: false, orderCodes: [], productSlugs: [], mediaIds: [], phone, checks: [] };
await mkdir('.artifacts', { recursive: true });
let password = process.env.QA_ADMIN_PASSWORD;
if (!password) { try { password = await readFile('/home/user/.kiya-qa-password', 'utf8'); } catch { password = randomBytes(24).toString('base64url'); await writeFile('/home/user/.kiya-qa-password', password, { mode: 0o600 }); } }
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const context = await browser.newContext({ baseURL: base, viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
page.setDefaultTimeout(12000);
const browserErrors = [];
page.on('pageerror', error => browserErrors.push(error.message));
const log = text => { records.checks.push(text); console.log(`PASS: ${text}`); };
const saveRecords = () => writeFile('.artifacts/test-records.json', JSON.stringify(records, null, 2));
async function navigate(path) { await page.goto(path, { waitUntil: 'networkidle' }); }
async function adminTab(name) { await page.locator('.admin-sidebar nav').getByRole('button', { name, exact: false }).click(); }
try {
  const anonymous = await request.newContext({ baseURL: base });
  expect((await anonymous.get('/api/admin')).status()).toBe(401);
  expect((await anonymous.post('/api/admin', { data: { action: 'product.archive', id: 1 } })).status()).toBe(401);
  expect((await anonymous.post('/api/admin/auth', { headers: { Origin: 'https://untrusted.example' }, data: { action: 'setup', password: 'invalid' } })).status()).toBe(403);
  await anonymous.dispose(); log('Admin authorization and cross-origin protections');
  const initialStore = await (await context.request.get('/api/shop')).json();
  records.originalHeroTitle = initialStore.settings.heroTitle; await saveRecords();
  const belt = initialStore.products.find(p => p.slug === 'classic-leather-belt');
  expect(belt).toBeTruthy(); const initialStock = belt.stock;
  await navigate('/'); await expect(page.getByRole('heading', { name: new RegExp(initialStore.settings.heroTitle) })).toBeVisible();
  await page.getByRole('button', { name: 'تغییر به تم روشن', exact: true }).click();
  expect(await page.locator('html').getAttribute('data-theme')).toBe('light');
  await page.reload({ waitUntil: 'networkidle' }); expect(await page.locator('html').getAttribute('data-theme')).toBe('light');
  await page.getByRole('button', { name: 'تغییر به تم تاریک', exact: true }).click(); log('Theme switching and persistence');
  await page.getByRole('button', { name: `افزودن ${belt.name} به علاقه‌مندی‌ها`, exact: true }).first().click();
  await page.getByRole('button', { name: 'مشاهده علاقه‌مندی‌ها', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText(belt.name); await page.keyboard.press('Escape');
  await page.reload({ waitUntil: 'networkidle' });
  await expect(page.getByRole('button', { name: `حذف ${belt.name} از علاقه‌مندی‌ها`, exact: true }).first()).toBeVisible(); log('Persistent favorites and accessible modal dismissal');
  await page.getByRole('button', { name: `انتخاب و خرید ${belt.name}`, exact: true }).first().click();
  await page.getByRole('dialog').getByRole('button', { name: '۱۱۰', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'افزودن به سبد خرید', exact: true }).click();
  await page.getByRole('button', { name: /سبد خرید،/ }).click();
  await expect(page.locator('.cart-item')).toContainText('110');
  await page.getByRole('dialog').getByRole('button', { name: 'افزایش تعداد', exact: true }).click();
  await expect(page.locator('.cart-item .quantity>span')).toHaveText('۲');
  await page.getByRole('dialog').getByRole('button', { name: 'کاهش تعداد', exact: true }).click();
  await expect(page.locator('.cart-item .quantity>span')).toHaveText('۱');
  await page.screenshot({ path: '.artifacts/cart.png' }); await page.keyboard.press('Escape');
  await page.reload({ waitUntil: 'networkidle' });
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('kiya-cart'))[0].size)).toBe('110'); log('Variant selection, cart quantity controls and persistence');
  await page.getByLabel('جستجو در محصولات', { exact: true }).fill('انگشتر');
  await page.getByLabel('جستجو در محصولات', { exact: true }).press('Enter');
  await page.waitForURL(/\/shop\?q=/); await expect(page.locator('.catalog-product-grid .product-card')).toHaveCount(initialStore.products.filter(p => `${p.name} ${p.description}`.includes('انگشتر')).length);
  await page.getByRole('button', { name: 'حذف همه', exact: true }).click();
  await page.getByRole('radio', { name: /^کمربند/ }).check();
  await expect(page.locator('.catalog-product-grid .product-card')).toHaveCount(2);
  await page.locator('#max-price').focus(); await page.keyboard.press('Home'); await expect(page.getByRole('heading', { name: 'این‌بار چیزی پیدا نشد' })).toBeVisible();
  await page.getByRole('button', { name: 'نمایش همهٔ محصولات', exact: true }).click();
  await page.getByLabel('مرتب‌سازی محصولات', { exact: true }).selectOption('price-asc');
  const firstName = await page.locator('.catalog-product-grid .product-card h3').first().innerText();
  expect(firstName).toBe(initialStore.products.slice().sort((a, b) => a.price - b.price)[0].name); log('Search, category and price filters, sorting and empty state');
  let orderPayload;
  await page.route('**/api/orders', async route => {
    if (route.request().method() !== 'POST') return route.continue();
    const body = route.request().postDataJSON();
    orderPayload = { ...body, total: 1, subtotal: 1, items: body.items.map(item => ({ ...item, price: 1 })) };
    await route.continue({ postData: JSON.stringify(orderPayload) });
  });
  await navigate('/checkout');
  await page.getByLabel('نام و نام خانوادگی', { exact: true }).fill('آزمون خودکار کیا');
  await page.getByLabel('شماره موبایل', { exact: true }).fill(phone);
  await page.getByLabel('شهر', { exact: true }).fill('تهران');
  await page.getByLabel('کد پستی', { exact: true }).fill('1111111111');
  await page.getByLabel('آدرس کامل', { exact: true }).fill('تهران، خیابان آزمایشی، پلاک ۱، واحد ۱');
  await page.getByLabel('کد تخفیف', { exact: true }).fill('WELCOME10');
  await page.getByRole('button', { name: 'اعمال کد', exact: true }).click();
  await expect(page.locator('.applied-coupon')).toContainText('WELCOME10');
  await page.locator('.terms-checkbox input').check();
  await page.getByRole('button', { name: 'ثبت سفارش و دریافت کد پیگیری', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'یک انتخاب خوب، ثبت شد!' })).toBeVisible();
  const code = await page.locator('.success-code>b').innerText(); records.orderCodes.push(code); await saveRecords();
  await page.screenshot({ path: '.artifacts/order-success.png', fullPage: true });
  const lookup = await (await context.request.post('/api/orders/track', { data: { code, phone } })).json();
  const expectedTotal = belt.price - Math.floor(belt.price * .1) + (belt.price >= initialStore.settings.shippingThreshold ? 0 : initialStore.settings.shippingCost);
  expect(lookup.order.total).toBe(expectedTotal);
  let catalog = await (await context.request.get('/api/shop')).json(); expect(catalog.products.find(p => p.id === belt.id).stock).toBe(initialStock - 1);
  const replay = await (await context.request.post('/api/orders', { data: orderPayload })).json(); expect(replay.code).toBe(code);
  catalog = await (await context.request.get('/api/shop')).json(); expect(catalog.products.find(p => p.id === belt.id).stock).toBe(initialStock - 1);
  const invalidQuantity = await context.request.post('/api/orders', { data: { ...orderPayload, requestKey: crypto.randomUUID(), items: [{ ...orderPayload.items[0], quantity: 999 }] } }); expect(invalidQuantity.status()).toBe(400);
  log('Checkout, coupon, server pricing, atomic stock, idempotency and quantity validation');
  await page.unroute('**/api/orders');
  await page.locator('.order-success').getByRole('link', { name: 'پیگیری سفارش', exact: true }).click();
  await page.getByLabel('شماره موبایل', { exact: true }).fill(phone);
  await page.getByRole('button', { name: 'پیگیری سفارش', exact: true }).click();
  await expect(page.locator('.tracked-order')).toContainText(code);
  await expect(page.locator('.tracked-order')).toContainText('در انتظار تأیید');
  expect((await context.request.post('/api/orders/track', { data: { code, phone: '09111111111' } })).status()).toBe(404); log('Order tracking and phone-bound order privacy');
  await navigate('/');
  await page.getByLabel('شماره موبایل', { exact: true }).fill(phone);
  await page.getByRole('button', { name: 'منم هستم', exact: true }).click();
  await expect(page.locator('.newsletter-success')).toBeVisible();
  await page.getByRole('button', { name: 'تماس با ما', exact: true }).click();
  await page.getByRole('dialog').getByLabel('نام شما', { exact: true }).fill('پیام آزمون خودکار');
  await page.getByRole('dialog').getByLabel('شماره موبایل', { exact: true }).fill(phone);
  await page.getByRole('dialog').getByLabel('پیام شما', { exact: true }).fill('این پیام فقط برای بررسی ذخیره و مدیریت پیام مشتری ایجاد شده است.');
  await page.getByRole('dialog').getByRole('button', { name: 'ارسال پیام', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'پیامت به دستمون رسید', exact: true })).toBeVisible(); await page.keyboard.press('Escape'); log('Newsletter registration and persisted support messages');
  const authInfo = await (await context.request.get('/api/admin/auth')).json();
  if (!authInfo.configured && authInfo.setupKeyRequired) {
    const rejectedSetup = await context.request.post('/api/admin/auth', { data: { action: 'setup', password, setupKey: 'incorrect-owner-key' } });
    expect(rejectedSetup.status()).toBe(403); log('Owner-only first-run setup rejects an incorrect activation key');
  }
  await navigate('/admin');
  if (!authInfo.configured) {
    await page.locator('input[autocomplete="new-password"]').nth(0).fill(password);
    await page.locator('input[autocomplete="new-password"]').nth(1).fill(password);
    if (authInfo.setupKeyRequired) await page.getByLabel('کلید امن راه‌اندازی', { exact: true }).fill(process.env.ADMIN_SETUP_KEY || '');
    await page.getByRole('button', { name: 'راه‌اندازی امن پنل', exact: true }).click(); records.createdAdmin = true; await saveRecords();
  } else {
    await page.locator('input[autocomplete="current-password"]').fill(password);
    await page.getByRole('button', { name: 'ورود به پنل مدیریت', exact: true }).click();
  }
  await expect(page.locator('.admin-app')).toBeVisible();
  await page.screenshot({ path: '.artifacts/admin-dashboard.png', fullPage: true }); log('Secure first-run administrator setup and dashboard');
  await adminTab('سفارش‌ها');
  await page.getByRole('button', { name: `مدیریت سفارش ${code}`, exact: true }).click();
  await page.getByRole('dialog').getByRole('combobox', { name: 'وضعیت سفارش', exact: true }).selectOption('confirmed');
  await page.getByRole('dialog').getByRole('button', { name: 'ثبت تغییرات سفارش', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const confirmed = await (await context.request.post('/api/orders/track', { data: { code, phone } })).json(); expect(confirmed.order.status).toBe('confirmed'); log('Order processing in administration updates public tracking');
  await adminTab('ویترین و بنرها');
  await page.getByLabel('خط اول عنوان', { exact: true }).fill('جزئیات خاص،');
  await page.getByRole('button', { name: 'انتشار تغییرات بنر', exact: true }).click();
  await expect.poll(async () => (await (await context.request.get('/api/shop')).json()).settings.heroTitle).toBe('جزئیات خاص،');
  const preview = await context.newPage(); await preview.goto('/', { waitUntil: 'networkidle' }); await expect(preview.locator('.hero-copy h1')).toContainText('جزئیات خاص،'); await preview.close();
  await page.getByLabel('خط اول عنوان', { exact: true }).fill(initialStore.settings.heroTitle);
  await page.getByRole('button', { name: 'انتشار تغییرات بنر', exact: true }).click();
  await expect.poll(async () => (await (await context.request.get('/api/shop')).json()).settings.heroTitle).toBe(initialStore.settings.heroTitle); log('Banner editing persisted and reflected in the storefront');
  await adminTab('محصولات و موجودی');
  await page.getByRole('button', { name: 'محصول جدید', exact: true }).click();
  const dialog = page.getByRole('dialog'); const slug = `qa-product-${Date.now()}`; records.productSlugs.push(slug); await saveRecords();
  await dialog.getByLabel('نام محصول', { exact: true }).fill('محصول آزمون خودکار');
  await dialog.getByLabel('شناسهٔ انگلیسی (اختیاری)', { exact: true }).fill(slug);
  await dialog.getByLabel('قیمت فروش (تومان)', { exact: true }).fill('123000');
  await dialog.getByLabel('موجودی انبار', { exact: true }).fill('3');
  const uploadResponse = page.waitForResponse(response => response.url().endsWith('/api/admin/media') && response.request().method() === 'POST');
  await dialog.locator('input[type=file]').first().setInputFiles('public/images/product-belt.webp');
  const uploaded = await (await uploadResponse).json(); expect(uploaded.id).toBeTruthy(); records.mediaIds.push(uploaded.id); await saveRecords();
  await expect(dialog.locator('.image-picker-preview img').first()).toHaveAttribute('src', uploaded.url);
  await dialog.getByRole('button', { name: 'ذخیرهٔ محصول', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const productRow = page.locator('tr').filter({ hasText: slug }); await expect(productRow).toBeVisible();
  await page.screenshot({ path: '.artifacts/admin-products.png', fullPage: true });
  page.once('dialog', d => d.accept()); await productRow.getByRole('button', { name: 'بایگانی محصول آزمون خودکار', exact: true }).click();
  await expect(productRow).toHaveClass(/archived-row/); log('Product creation, optimized image upload and reversible archiving');
  await adminTab('کدهای تخفیف');
  await page.getByRole('button', { name: 'کد تخفیف جدید', exact: true }).click();
  await page.getByRole('dialog').getByLabel('کد تخفیف (انگلیسی)', { exact: true }).fill('QA10');
  await page.getByRole('dialog').getByRole('button', { name: 'ذخیرهٔ کد تخفیف', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const qaCoupon = await (await context.request.post('/api/coupon', { data: { code: 'QA10', lines: [{ productId: belt.id, price: belt.price, quantity: 1, category: belt.category }], phone } })).json(); expect(qaCoupon.percent).toBe(10); expect(qaCoupon.amount).toBe(Math.round(belt.price * 0.1)); log('Coupon administration');
  await adminTab('پیام‌های مشتریان');
  const message = page.locator('.admin-message-card').filter({ hasText: 'پیام آزمون خودکار' }).first();
  await message.getByRole('button', { name: 'خواندم', exact: true }).click(); await expect(message).toContainText('خوانده شده'); log('Support inbox and read status');
  await adminTab('سفارش‌ها');
  await page.getByRole('button', { name: `مدیریت سفارش ${code}`, exact: true }).click();
  await page.getByRole('dialog').getByRole('combobox', { name: 'وضعیت سفارش', exact: true }).selectOption('cancelled');
  await page.getByRole('dialog').getByRole('checkbox').check();
  await page.getByRole('dialog').getByRole('button', { name: 'ثبت تغییرات سفارش', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  catalog = await (await context.request.get('/api/shop')).json(); expect(catalog.products.find(p => p.id === belt.id).stock).toBe(initialStock); log('Cancellation restores stock atomically');
  const cookie = (await context.cookies()).find(c => c.name === 'kiya_admin_session');
  expect(cookie.httpOnly).toBe(true); expect(cookie.secure).toBe(process.env.NODE_ENV === 'production');
  const staleSession = await request.newContext({ baseURL: base, extraHTTPHeaders: { Cookie: `kiya_admin_session=${cookie.value}` } });
  await adminTab('تنظیمات فروشگاه');
  const newPassword = randomBytes(24).toString('base64url');
  await page.getByLabel('رمز فعلی', { exact: true }).fill(password);
  await page.getByLabel('رمز جدید', { exact: true }).fill(newPassword);
  await page.getByLabel('تکرار رمز جدید', { exact: true }).fill(newPassword);
  await page.getByRole('button', { name: 'ذخیرهٔ رمز جدید', exact: true }).click();
  await expect(page.getByLabel('رمز فعلی', { exact: true })).toHaveValue('');
  password = newPassword; await writeFile('/home/user/.kiya-qa-password', password, { mode: 0o600 });
  expect((await staleSession.get('/api/admin')).status()).toBe(401); await staleSession.dispose();
  expect((await context.request.get('/api/admin')).status()).toBe(200);
  await page.getByRole('button', { name: 'خروج از حساب مدیر', exact: true }).click();
  await expect(page.getByRole('button', { name: 'ورود به پنل مدیریت', exact: true })).toBeVisible();
  await page.locator('input[autocomplete="current-password"]').fill(password);
  await page.getByRole('button', { name: 'ورود به پنل مدیریت', exact: true }).click();
  await expect(page.locator('.admin-app')).toBeVisible();
  await page.getByRole('button', { name: 'خروج از حساب مدیر', exact: true }).click(); log('Password rotation, HttpOnly secure cookie, session revocation and login/logout');
  const manifest = await (await context.request.get('/manifest.webmanifest')).json(); expect(manifest.display).toBe('standalone');
  await navigate('/'); expect(await page.evaluate(async () => !!(await navigator.serviceWorker.ready))).toBe(true);
  const offlinePage = await context.newPage(); await offlinePage.goto('/', { waitUntil: 'networkidle' });
  await context.setOffline(true); await offlinePage.goto('/offline-check', { waitUntil: 'domcontentloaded' });
  await expect(offlinePage.getByRole('heading', { name: 'یه لحظه از هم دور شدیم.' })).toBeVisible(); await context.setOffline(false); await offlinePage.close(); log('Installable PWA manifest, service worker and safe offline fallback');
  expect(browserErrors).toEqual([]); log('No client-side runtime errors');
  await saveRecords(); console.log(`All ${records.checks.length} functional checks passed. Test data recorded for cleanup.`);
} catch (error) {
  await saveRecords(); await page.screenshot({ path: '.artifacts/test-failure.png', fullPage: true }).catch(() => {});
  console.error(error); console.error('Browser errors:', browserErrors); process.exitCode = 1;
} finally { await browser.close(); }
