"use client";
import { useState, useEffect, useRef, type ReactNode, type FormEvent } from "react";
import Link from "next/link";
import { useRouter, usePathname } from "next/navigation";
import { Search, Heart, ShoppingBag, UserRound, Sun, Moon, ArrowLeft, ArrowUpLeft, ChevronDown, ChevronLeft, LayoutGrid, Truck, Download, PackageSearch, Zap, Handshake, X, Camera as Instagram, Send, Headphones, ShieldCheck, Smartphone, Plus, Menu, Trash2, Check, MapPin, Phone, Sparkles, Newspaper } from "lucide-react";
import { type Product, type ShopSettings, categories, money, digits, defaultMenus, type MenuLink } from "@/lib/catalog";
import { useShop } from "./shop-provider";
import { trackEvent } from "@/lib/client-analytics";
import { Brand, Modal, Quantity, EmptyState } from "./ui";
import { TrackOrder } from "./track-order";
import { AiStylistWidget } from "./ai-stylist";

type Overlay = "cart" | "favorites" | "track" | "contact" | "install" | "about" | "shipping" | "returns" | "privacy" | null;
export function StoreShell({ products, settings, children }: { products: Product[]; settings: ShopSettings; children: ReactNode }) {
  const shop = useShop(); const router = useRouter(); const pathname = usePathname();
  const [announcement, setAnnouncement] = useState(true);
  const [overlay, setOverlay] = useState<Overlay>(null);
  // فاز ۱۳: منوها از تنظیمات پنل؛ نبود تنظیم = پیش‌فرض داخلی (بدون تغییر ظاهر)
  const menus = settings.menus && Array.isArray(settings.menus.header) ? settings.menus : defaultMenus;
  const openOverlayKey = (key: string) => { if (["shipping", "returns", "about", "contact", "privacy"].includes(key)) setOverlay(key as Overlay); };
  const [query, setQuery] = useState(""); const [searchOpen, setSearchOpen] = useState(false);
  const [categoriesOpen, setCategoriesOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  useEffect(() => { setOverlay(null); setCategoriesOpen(false); setSearchOpen(false); }, [pathname]);
  useEffect(() => { const close = (e: MouseEvent) => { if (!menuRef.current?.contains(e.target as Node)) setCategoriesOpen(false); }; document.addEventListener("click", close); return () => document.removeEventListener("click", close); }, []);
  const matching = products.filter(p => `${p.name} ${p.material}`.includes(query.trim())).slice(0, 5);
  const total = shop.cart.reduce((sum, p) => sum + p.quantity * p.price, 0);
  const count = shop.cart.reduce((sum, p) => sum + p.quantity, 0);
  const favoriteProducts = products.filter(p => shop.favorites.includes(p.id));
  function search(event: FormEvent) { event.preventDefault(); setSearchOpen(false); if (query.trim()) trackEvent("search", query.trim(), false); router.push(`/shop${query.trim() ? `?q=${encodeURIComponent(query.trim())}` : ""}`); }
  async function install() { if (shop.installed) { shop.toast("اپلیکیشن کیا روی دستگاهت نصب شده است."); return; } if (!await shop.install()) setOverlay("install"); }
  function social(url: string) { if (url) window.open(url, "_blank", "noopener,noreferrer"); else setOverlay("contact"); }
  const labels: Record<Exclude<Overlay, null>, string> = { cart: "سبد خرید تو", favorites: "علاقه‌مندی‌های تو", track: "پیگیری سفارش", contact: "با کیا در ارتباط باش", install: "کیا، همیشه همراه تو", about: "کیا؛ جزئیات، امضای تو", shipping: "روش‌های ارسال و تحویل", returns: "راهنمای بازگشت کالا", privacy: "حریم خصوصی و شرایط خرید" };
  return <>
    <a className="skip-link" href="#main-content">رفتن به محتوای اصلی</a>
    {announcement && <div className="announcement"><div className="container announcement-content"><span><Sparkles size={14} />{settings.announcement}<i />ارسال رایگان برای خریدهای بالای {money(settings.shippingThreshold)} تومان</span><Link href="/shop">وقتِ خوش‌استایل شدنه <ArrowLeft size={13} /></Link><button aria-label="بستن اطلاعیه" onClick={() => setAnnouncement(false)}><X size={14} /></button></div></div>}
    <header className="site-header"><div className="container header-main"><Brand /><form className="search-form" onSubmit={search}><Search size={20} /><input aria-label="جستجو در محصولات" placeholder="دنبال چه جزئیاتی برای استایلت می‌گردی؟" value={query} onChange={e => { setQuery(e.target.value); setSearchOpen(true); }} onFocus={() => setSearchOpen(true)} onBlur={() => setTimeout(() => setSearchOpen(false), 180)} /><kbd>جستجو</kbd>{searchOpen && query.trim() && <div className="search-results"><span className="search-label">نتیجه‌های پیشنهادی</span>{matching.length ? matching.map(p => <Link href={`/product/${p.slug}`} key={p.id} onClick={() => setSearchOpen(false)}><img src={p.image} alt="" width="42" height="42" /><span>{p.name}<small>{money(p.price)} تومان</small></span><ChevronLeft size={16} /></Link>) : <p>محصولی پیدا نشد. عبارت دیگری امتحان کن.</p>}<button type="submit">مشاهدهٔ همهٔ نتایج <ArrowLeft size={15} /></button><button type="button" className="ai-search-hint" onMouseDown={e => e.preventDefault()} onClick={() => { setSearchOpen(false); window.dispatchEvent(new CustomEvent("kiya:ai", { detail: { message: query.trim() } })); }}><Sparkles size={14} />از مشاور هوشمند کیا بپرس</button></div>}</form><div className="header-actions"><button className="icon-button theme-toggle" aria-label={shop.theme === "dark" ? "تغییر به تم روشن" : "تغییر به تم تاریک"} onClick={shop.toggleTheme}>{shop.theme === "dark" ? <Sun size={20} /> : <Moon size={20} />}</button><span className="action-separator" /><Link className="icon-button account-button" href="/account" aria-label="حساب کاربری من"><UserRound size={21} /></Link><button className="icon-button favorite-header" aria-label="مشاهده علاقه‌مندی‌ها" onClick={() => setOverlay("favorites")}><Heart size={21} />{shop.favorites.length > 0 && <i className="mini-dot" />}</button><button className="cart-button" onClick={() => setOverlay("cart")} aria-label={`سبد خرید، ${count} محصول`}><ShoppingBag size={21} /><span>سبد خرید</span><b>{money(count)}</b></button></div></div>
    <div className="nav-border"><nav className="container main-nav" aria-label="منوی اصلی"><div className="category-menu" ref={menuRef}><button className={`category-toggle ${categoriesOpen ? "active" : ""}`} onClick={() => setCategoriesOpen(!categoriesOpen)} aria-expanded={categoriesOpen}><LayoutGrid size={18} />دسته‌بندی محصولات<ChevronDown size={14} /></button>{categoriesOpen && <div className="category-dropdown">{categories.map(c => <Link key={c.id} href={`/shop?category=${c.id}`} onClick={() => setCategoriesOpen(false)}>{c.name}<ChevronLeft size={16} /></Link>)}<Link href="/shop" onClick={() => setCategoriesOpen(false)}>همهٔ محصولات <ArrowLeft size={16} /></Link></div>}</div><span className="nav-divider" /><div className="nav-links">{menus.header.slice(0, 12).map((item, index) => <NavItem key={`${item.href}-${index}`} item={item} pathname={pathname} />)}</div><div className="nav-extras"><Link href="/track"><PackageSearch size={17} />پیگیری سفارش</Link><button onClick={install}><Download size={16} /><span>{shop.installed ? "اپلیکیشن نصب شده" : "نصب اپلیکیشن"}</span></button></div></nav></div></header>
    <main id="main-content">{children}</main>
    <footer className="site-footer"><div className="container"><div className="footer-main"><div className="footer-brand"><Brand /><p>ما در کیا به قدرت جزئیات باور داریم. کمربند و اکسسوری‌هایی دست‌چین می‌کنیم که به استایل تو، امضای خودت رو اضافه کنن.</p><div className="social-links"><button onClick={() => social(settings.instagramUrl)} aria-label="اینستاگرام کیا"><Instagram size={19} /></button><button onClick={() => social(settings.telegramUrl)} aria-label="کانال تلگرام کیا"><Send size={18} /></button><button onClick={() => social(settings.botUrl)} aria-label="ربات تلگرام کیا"><Smartphone size={19} /></button></div></div><FooterColumn title={menus.shopTitle} links={menus.shop} onOverlay={openOverlayKey} /><FooterColumn title={menus.helpTitle} links={menus.help} onOverlay={openOverlayKey} /><div className="footer-connect"><h3>فقط یک پیام با هم فاصله داریم</h3><p>برای انتخاب، سایز یا پیگیری خریدت، روی کمک ما حساب کن.</p><button className="button button-outline" onClick={() => setOverlay("contact")}><Headphones size={18} />گفت‌وگو با پشتیبانی<ArrowUpLeft size={17} /></button><button className="footer-install" onClick={install}><Smartphone size={17} />نصب نسخهٔ وب‌اپلیکیشن<ArrowLeft size={16} /></button></div></div><div className="footer-bottom"><span>تمام حقوق برای <strong>{settings.storeName}</strong> محفوظ است. © {money(1405)}</span><span className="footer-bottom-links"><button onClick={() => setOverlay("privacy")}>حریم خصوصی</button><i /><Link href="/admin">مدیریت فروشگاه</Link></span><span className="footer-signature" dir="ltr">IT’S ALL IN THE DETAILS.</span></div></div></footer>
    <AiStylistWidget />
    <div className="mobile-bottom-nav"><Link href="/"><LayoutGrid size={20} /><span>خانه</span></Link><Link href="/shop"><Search size={20} /><span>فروشگاه</span></Link><button onClick={() => setOverlay("cart")}><ShoppingBag size={21} /><span>سبد خرید {count > 0 && `(${money(count)})`}</span></button><button onClick={() => setOverlay("favorites")}><Heart size={20} /><span>علاقه‌مندی</span></button><button onClick={() => setOverlay("track")}><UserRound size={20} /><span>سفارش من</span></button></div>
    {overlay && <Modal title={labels[overlay]} drawer={overlay === "cart"} onClose={() => setOverlay(null)}>
      {overlay === "cart" && <div className="cart-content">{shop.cart.length ? <><div className="shipping-progress"><Truck size={20} /><p>{total >= settings.shippingThreshold ? "ارسال این سفارش مهمون مایی!" : <>{money(settings.shippingThreshold - total)} تومان تا ارسال رایگان</>}</p><div><span style={{ width: `${Math.min(100, total / Math.max(1, settings.shippingThreshold) * 100)}%` }} /></div></div><div className="cart-items">{shop.cart.map(item => <div className="cart-item" key={item.key}><Link href={`/product/${item.slug}`} onClick={() => setOverlay(null)}><img src={item.image} alt={item.name} width="85" height="95" /></Link><div><Link href={`/product/${item.slug}`} onClick={() => setOverlay(null)}><h3>{item.name}</h3></Link><p>{item.color} · سایز {item.size}</p><span>{money(item.price)} <small>تومان</small></span><div className="cart-item-actions"><Quantity value={item.quantity} max={Math.min(item.stock, 10)} onChange={n => shop.updateQuantity(item.key, n)} /><button className="icon-button" aria-label={`حذف ${item.name}`} onClick={() => shop.updateQuantity(item.key, 0)}><Trash2 size={15} /></button></div></div></div>)}</div><div className="cart-summary"><div><span>جمع سبد خرید</span><strong>{money(total)} <small>تومان</small></strong></div><p>هزینهٔ ارسال و تخفیف در مرحلهٔ بعد محاسبه می‌شود.</p><Link className="button button-lime" href="/checkout" onClick={() => setOverlay(null)}>ادامه و ثبت سفارش<ArrowLeft size={18} /></Link><button className="text-link" onClick={() => setOverlay(null)}>ادامهٔ گشت‌وگذار در فروشگاه</button></div></> : <EmptyState icon={<ShoppingBag size={37} />} title="سبدت منتظر یک انتخاب خوبه" text="از بین جزئیات کیا، چیزی که به استایلت میاد رو پیدا کن."><Link className="button button-lime" href="/shop" onClick={() => setOverlay(null)}>بریم فروشگاه <ArrowLeft size={17} /></Link></EmptyState>}</div>}
      {overlay === "favorites" && (favoriteProducts.length ? <div className="favorite-list">{favoriteProducts.map(p => <div key={p.id}><Link href={`/product/${p.slug}`} onClick={() => setOverlay(null)}><img src={p.image} alt={p.name} width="85" height="85" /></Link><span><Link href={`/product/${p.slug}`} onClick={() => setOverlay(null)}>{p.name}</Link><small>{money(p.price)} تومان</small></span><button className="icon-button is-favorite" aria-label={`حذف ${p.name} از علاقه‌مندی‌ها`} onClick={() => shop.toggleFavorite(p.id)}><Heart size={20} fill="currentColor" /></button></div>)}</div> : <EmptyState icon={<Heart size={35} />} title="انتخاب‌های دوست‌داشتنی‌ات اینجان" text="روی قلب محصولات بزن تا برای بعد نگه‌شان داری." />)}
      {overlay === "track" && <TrackOrder />}
      {overlay === "contact" && <ContactForm settings={settings} />}
      {overlay === "install" && <div className="install-content"><img src="/images/icon-192.png" width="86" height="86" alt="اپلیکیشن کیا" /><h3>فروشگاهت رو به صفحهٔ اصلی بیار</h3><p>بدون نیاز به دانلود از اپ‌استور؛ سریع، سبک و همیشه در دسترس.</p><div><strong>در اندروید و Chrome</strong><p>از منوی مرورگر <b>⋮</b> گزینهٔ «Install app» یا «Add to Home screen» را انتخاب کن.</p></div><div><strong>در آیفون و Safari</strong><p>دکمهٔ اشتراک‌گذاری را بزن و «Add to Home Screen» را انتخاب کن.</p></div><small>نصب در مرورگر اصلی و اتصال HTTPS در دسترس است. اگر صفحه داخل پیش‌نمایش باز شده، آن را در یک تب مستقل باز کن.</small></div>}
      {overlay === "about" && <div className="prose"><span className="large-wordmark" dir="ltr">KIYA.</span><h3>استایل از جزئیات شروع می‌شه.</h3><p>کیا از علاقه به جزئیات به وجود آمده؛ از یک سگک خوش‌ساخت تا فرم سادهٔ یک انگشتر. ما کمربند، بدلیجات و اکسسوری‌هایی انتخاب می‌کنیم که هم برای هر روز مناسب باشند و هم حس متفاوتی به استایلت بدهند.</p><p>این فروشگاه، امتداد آنلاین مغازهٔ ماست؛ جایی برای دیدن، مقایسه‌کردن و انتخاب‌کردن با خیال راحت.</p><Link className="button button-lime" href="/shop" onClick={() => setOverlay(null)}>کالکشن کیا را ببین <ArrowLeft size={17} /></Link></div>}
      {overlay === "shipping" && <div className="prose"><Truck size={34} /><h3>از کیا، تا درِ خانهٔ تو</h3><p>سفارش بعد از بررسی موجودی و تأیید فروشگاه آمادهٔ ارسال می‌شود. زمان و روش ارسال در تماس تأیید سفارش با شما هماهنگ خواهد شد.</p><p>هزینهٔ ارسال {money(settings.shippingCost)} تومان است و برای خریدهای بالای {money(settings.shippingThreshold)} تومان رایگان می‌شود.</p><p>{settings.address ? `تحویل حضوری با هماهنگی در فروشگاه: ${settings.address}` : "برای اطلاع از امکان تحویل حضوری، به پشتیبانی پیام بدهید."}</p><p>کد رهگیری پس از ارسال در صفحهٔ پیگیری سفارش ثبت می‌شود.</p></div>}
      {overlay === "returns" && <div className="prose"><ShieldCheck size={34} /><h3>انتخابت باید با خیال راحت باشه</h3><p>تا ۷ روز پس از تحویل، در صورت استفاده‌نشدن و سالم‌بودن کالا و بسته‌بندی، درخواست بررسی بازگشت را از طریق پشتیبانی ثبت کنید.</p><p>برای کالاهای بهداشتی مثل گوشواره، بازشدن پلمپ یا استفاده از محصول می‌تواند امکان بازگشت را محدود کند. سفارش‌های شخصی‌سازی‌شده پیش از خرید نیاز به هماهنگی دارند.</p><p>در صورت ایراد یا مغایرت، شمارهٔ سفارش و عکس کالا را برای بررسی نگه دارید. قبل از ارسال مجدد، با فروشگاه هماهنگ کنید.</p><button className="button button-outline" onClick={() => setOverlay("contact")}>ثبت پیام برای پشتیبانی</button></div>}
      {overlay === "privacy" && <div className="prose"><h3>اطلاعاتت پیش ما امانته</h3><p>نام، شماره تماس و نشانی فقط برای ثبت، پیگیری و تحویل سفارش ذخیره می‌شود. سبد خرید، علاقه‌مندی‌ها و انتخاب تم در حافظهٔ مرورگر شما نگه‌داری می‌شوند.</p><p>با عضویت در خبرنامه، شمارهٔ شما برای اطلاع‌رسانی کالکشن‌ها ذخیره می‌شود؛ برای درخواست حذف اطلاعات یا لغو عضویت، از بخش تماس با ما پیام بگذارید.</p><p>ثبت سفارش به معنی پرداخت نیست. قیمت و موجودی در سرور بررسی می‌شوند و تأیید نهایی خرید و روش پرداخت با فروشگاه هماهنگ خواهد شد.</p><p>این نسخه با کاتالوگ اولیهٔ نمایشی راه‌اندازی شده است. تصاویر، مشخصات، قیمت‌ها و سیاست‌های فروش باید پیش از شروع فروش واقعی توسط مدیر تأیید شوند.</p></div>}
    </Modal>}
  </>;
}

function ContactForm({ settings }: { settings: ShopSettings }) {
  const [loading, setLoading] = useState(false); const [sent, setSent] = useState(false); const [error, setError] = useState("");
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setError(""); const values = Object.fromEntries(new FormData(e.currentTarget)); try { const response = await fetch("/api/community", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, type: "message" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSent(true); } catch (error) { setError(error instanceof Error ? error.message : "ارسال ناموفق بود."); } finally { setLoading(false); } }
  if (sent) return <EmptyState icon={<Check size={35} />} title="پیامت به دستمون رسید" text="پیام در صندوق پشتیبانی ثبت شد؛ از طریق شماره‌ای که وارد کردی باهات در ارتباط خواهیم بود." />;
  return <><p className="muted">برای انتخاب محصول، سایز یا هر سوالی، اینجا برامون بنویس.</p>{settings.supportPhone && <a className="contact-detail" href={`tel:${digits(settings.supportPhone)}`}><Phone size={18} /><span dir="ltr">{settings.supportPhone}</span></a>}{settings.address && <p className="contact-detail"><MapPin size={18} />{settings.address}</p>}<form className="form-stack" onSubmit={submit}><label>نام شما<input name="name" required minLength={2} maxLength={100} autoComplete="name" placeholder="نام و نام خانوادگی" /></label><label>شماره موبایل<input name="phone" required type="tel" autoComplete="tel" dir="ltr" placeholder="09xxxxxxxxx" /></label><label>پیام شما<textarea name="message" required minLength={10} maxLength={2000} rows={4} placeholder="چطور می‌تونیم کمکت کنیم؟" /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-lime" disabled={loading}>{loading ? "در حال ارسال..." : "ارسال پیام"}<Send size={17} /></button></form></>;
}

export function Newsletter() {
  const [phone, setPhone] = useState(""); const [loading, setLoading] = useState(false); const [joined, setJoined] = useState(false); const { toast } = useShop();
  async function submit(e: FormEvent) { e.preventDefault(); setLoading(true); try { const response = await fetch("/api/community", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "subscribe", phone }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setJoined(true); toast("به جمع خاص‌پسندهای کیا خوش اومدی!"); } catch (e) { toast(e instanceof Error ? e.message : "دوباره تلاش کنید.", "error"); } finally { setLoading(false); } }
  return <section className="newsletter"><div className="newsletter-icon"><Send size={31} /></div><div className="newsletter-copy"><span className="eyebrow">JOIN THE KIYA CLUB</span><h2>از خبرهای خوب، جا نمون.</h2><p>کالکشن‌های جدید و پیشنهادهای خاص، زودتر از همه برای تو.</p></div>{joined ? <div className="newsletter-success"><Check size={23} /><span>به خانوادهٔ کیا خوش اومدی!</span></div> : <form onSubmit={submit}><label className="sr-only" htmlFor="newsletter-phone">شماره موبایل</label><input id="newsletter-phone" type="tel" dir="rtl" placeholder="شماره موبایلت رو وارد کن" value={phone} onChange={e => setPhone(e.target.value)} required autoComplete="tel" /><button className="button button-lime" disabled={loading}>{loading ? "کمی صبر کن..." : "منم هستم"}<ArrowLeft size={18} /></button><small>بدون پیام‌های اضافه؛ فقط خبرهای خوب.</small></form>}</section>;
}


/* ============================================================
 *  فاز ۱۳ — منوی قابل مدیریت هدر و فوتر
 *  آیکون و استایل آیتم‌های خاص از روی href تشخیص داده می‌شود
 * ============================================================ */
function NavItem({ item, pathname }: { item: MenuLink; pathname: string }) {
  const active = pathname === item.href.split("?")[0] && !item.href.includes("?") ? "active" : "";
  if (item.href.includes("sale=1")) return <Link className={`offers-link ${active}`.trim()} href={item.href}><Zap size={15} />{item.label}</Link>;
  if (item.href === "/daily") return <Link className={active} href={item.href}><Newspaper size={15} />{item.label}</Link>;
  if (item.href === "/partner") return <Link className={`partner-nav-link ${active}`.trim()} href={item.href}><Handshake size={15} />{item.label}</Link>;
  if (item.href.includes("sort=newest")) return <Link href={item.href}>{item.label}<span className="new-dot" /></Link>;
  return <Link className={active} href={item.href}>{item.label}</Link>;
}

function FooterColumn({ title, links, onOverlay }: { title: string; links: MenuLink[]; onOverlay: (key: string) => void }) {
  return <div className="footer-column"><h3>{title}</h3>{links.slice(0, 12).map((link, index) => link.href.startsWith("#")
    ? <button key={`${link.href}-${index}`} onClick={() => onOverlay(link.href.slice(1))}>{link.label}</button>
    : <Link key={`${link.href}-${index}`} href={link.href}>{link.label}</Link>)}</div>;
}
